services:
  - type: web
    name: crypto-oraculo-vip
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"

  - type: worker
    name: crypto-oraculo-worker
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python worker.py"
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"
