services:
  - name: crypto-holdeo-bot
    type: worker
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    autoDeploy: true

    envVars:
      - key: TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: CAPITAL
        sync: false
