services:
  - name: crypto-holdeo-bot
    type: worker
    env: python
    region: oregon
    plan: starter   # free ya no existe para workers, starter es el v√°lido

    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    autoDeploy: true

    envVars:
      - key: TOKEN
        value: ${TOKEN}
      - key: CHAT_ID
        value: ${CHAT_ID}
      - key: CAPITAL
        value: ${CAPITAL}
